name: std
description: |-
  [std]
  A dependncy less dart package (CommandRunner etc).
version: 2026.112.1609
homepage: 
repository: https://github.com/dart-pkg/std
environment:
  sdk: ^3.7.2
platforms:
  android: 
  ios: 
  linux: 
  macos: 
  # web:
  windows: 
topics:
  - cli
  - process
dev_dependencies:
  debug_output: ^2025.504.1731
  lints: ^6.0.0
  test: ^1.29.0
dependencies:
  archive: ^4.0.7
  crypto: ^3.0.7
  encrypt: ^5.0.3
  http: ^1.6.0
  intl: ^0.20.2
  path: ^1.9.1
  system_info2: ^4.1.0
  uuid: ^4.5.2
